ongoing development

diff --git a/bin/onevim b/bin/onevim
--- a/bin/onevim
+++ b/bin/onevim
@@ -1,9 +1,11 @@
 #!/bin/bash
 # Name       : onevim
-# Description: Use MacVim in a single instance
+# Description: Use MacVim with server-driven instances
 #
 # Author     : github.com/reedes
 # Created    : February 17, 2014
+#
+# See Damian Conway's work on detecting multiple editing instances
 #
 # $ gvim --remote-send "<C-\><C-n>:if &ft == 'nerdtree'|wincmd p|endif|edit filename<CR>"
 # "help view" for startup modes
@@ -22,42 +24,78 @@
 # :hide            - close current window
 # :only            - keep only this window open
 
+# ===================================
+# Functions
+# ===================================
+
 # obtain the full path of a filename
 realpath() {
     [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
 }
 
+containsElement() {
+  local e
+  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
+  return 1
+}
+
+# ===================================
+# Entry point
+# ===================================
+
+if [ -z "$(which mvim)" ]; then
+  echo "ERROR: no mvim available"
+  exit(1)
+fi
+
+available_servers=($(mvim --serverlist))
+if [ $? -ne 0 ]; then
+  echo "ERROR: your mvim lacks client-server capability"
+  exit(1)
+fi
+
+# TODO use --servername= instead
+server_name=
+while getopts s: opt
+do
+  case $opt in
+  s)    server_name=$OPTARG
+        ;;
+  esac
+done
+shift $((OPTIND - 1))     # remove options, leave arguments
+#echo "server=$server remaining $@"
+
+# If no explicit server, choose one from list
+# but if none, choose VIM.
+if [ -z "$server_name" ] ; then
+  #server=$(cut -d" " -f2)
+  #server="${available_servers[@]:0:1}"
+  server="VIM"
+fi
+
 # determine the edit cmd from the name of the script
 # TODO view, sview
+more_keys=
 case "`basename "$0"`" in
-v*)
-  edit_cmd="vsplit"
-  more_keys="<c-w>L"     # right
-  ;;
-t*)
-  edit_cmd="tabedit"
-  more_keys=
-  ;;
-s*)
-  edit_cmd="split"
-  more_keys="<c-w>="          # equal
-  #more_keys="<c-w>_"          # maximize
-  ;;
-*)
-  edit_cmd="edit"
-  more_keys=
-  ;;
+v*)   edit_cmd="vsplit"
+      more_keys="<c-w>L"     # right
+      ;;
+t*)   edit_cmd="tabedit"
+      ;;
+s*)   edit_cmd="split"
+      more_keys="<c-w>="     # equal
+      ;;
+*)    edit_cmd="edit"
+      ;;
 esac
 
-# assume one or zero servers
-server=$( mvim --serverlist | head -n1 )
-if [ $? -ne 0 ]; then
-  # punt, because our vim lacks client server
-  mvim "$@"
-elif [ -n "$server" ] ; then
+server_exists=$(containsElement "$server_name" "${available_servers[@]}")
+
+if $server_exists ; then
   if [ $# -gt 1 ] ; then
     # load many files
-    mvim --server-name="$server" "$@" --remote-send ":call foreground()<CR>"
+    mvim --server-name="$server_name" "$@" --remote-send ":call foreground()<CR>"
   else
     keys=
     if [ -n "$1" ] ; then
@@ -65,12 +103,12 @@ elif [ -n "$server" ] ; then
       full_path=$(realpath "$1")
       keys="<C-\><C-n>:$edit_cmd $full_path<CR>"
     fi
-    mvim --server-name="$server" --remote-send ":call foreground()<CR>$keys$more_keys"
+    mvim --server-name="$server_name" --remote-send ":call foreground()<CR>$keys$more_keys"
   fi
 elif [ -n "$@" ] ; then
   # attempt to edit in a new server instance
-  mvim --remote-silent "$@"
+  mvim --server-name="$server_name" --remote-silent "$@"
 else
   # punt, because --remote-silent complains if no files
-  mvim
+  mvim #--server-name="$server_name" --remote-send ":call foreground()<CR>"
 fi
